---
title: "PolyATails Lengths"
author: '209509'
date: "2025-03-19"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load all data

```{r}
a60_30 <- read.table(file = 'a60_30_polyA_position.tsv', sep = '\t', header = TRUE)
a60_60 <- read.table(file = 'a60_60_polyA_position.tsv', sep = '\t', header = TRUE)
a60_unmod <- read.table(file = 'a60_unmod_polyA_position.tsv', sep = '\t', header = TRUE)

a120_1mod <- read.table(file = 'a120_1mod_polyA_position.tsv', sep = '\t', header = TRUE)
a120_2mod <- read.table(file = 'a120_2mod_polyA_position.tsv', sep = '\t', header = TRUE)
a120_4mod <- read.table(file = 'a120_4mod_polyA_position.tsv', sep = '\t', header = TRUE)
a120_unmod <- read.table(file = 'a120_unmod_polyA_position.tsv', sep = '\t', header = TRUE)
```

### Define lengths of polyAtail

```{r}
a60_30['polyA_length'] <- a60_30$end - a60_30$start
a60_60['polyA_length'] <- a60_60$end - a60_60$start
a60_unmod['polyA_length'] <- a60_unmod$end - a60_unmod$start

a120_1mod['polyA_length'] <- a120_1mod$end - a120_1mod$start
a120_2mod['polyA_length'] <- a120_2mod$end - a120_2mod$start
a120_4mod['polyA_length'] <- a120_4mod$end - a120_4mod$start
a120_unmod['polyA_length'] <- a120_unmod$end - a120_unmod$start
```


### Histograms of all the data

```{r}
# List of loaded datasets and their corresponding names
datasets <- list(
  a60_30 = a60_30,
  a60_60 = a60_60,
  a60_unmod = a60_unmod,
  a120_1mod = a120_1mod,
  a120_2mod = a120_2mod,
  a120_4mod = a120_4mod,
  a120_unmod = a120_unmod
)

for (name in names(datasets)) {
  polyA_length <- datasets[[name]]$polyA_length
  
  hist(polyA_length, 
       probability = TRUE, 
       main = paste("Density Plot of polyA Lengths -", name), 
       xlab = "PolyA Length", 
       ylab = "Density", 
       xlim = c(0, 6000),        
       ylim = c(0, 0.0020),     
       border = "black", 
       col = "lightblue",
       breaks = 200)              
  
  lines(density(polyA_length), col = "red", lwd = 2)
  }

```

### Histograms of all the data with log transformation

```{r}
for (name in names(datasets)) {
  polyA_length <- datasets[[name]]$polyA_length
  
  log_polyA_length <- log10(polyA_length) 
  
  hist(log_polyA_length, 
       probability = TRUE, 
       main = paste("Density Plot of log-transformed polyA Lengths -", name), 
       xlab = "Log10(PolyA Length)",
       ylab = "Density", 
       border = "black", 
       col = "lightblue",
       xlim = c(2.7,4),
       ylim = c(0,11),
       breaks = 100)                  
  
  lines(density(log_polyA_length), col = "red", lwd = 2)
}
```


