---
title: "Adapter lengths for all datasets"
output:
  pdf_document: default
  html_document: default
date: "2025-03-19"
---

### Load all data

```{r}
a60_unmod <- read.table(file = "a60_unmod_polyA_position.tsv", sep = "\t", header = TRUE)
a60_30 <- read.table(file = "a60_30_polyA_position.tsv", sep = "\t", header = TRUE)
a60_60 <- read.table(file = "a60_60_polyA_position.tsv", sep = "\t", header = TRUE)

a120_unmod <- read.table(file = "a120_unmod_polyA_position.tsv", sep = "\t", header = TRUE)
a120_1mod <- read.table(file = "a120_1mod_polyA_position.tsv", sep = "\t", header = TRUE)
a120_2mod <- read.table(file = "a120_2mod_polyA_position.tsv", sep = "\t", header = TRUE)
a120_4mod <- read.table(file = "a120_4mod_polyA_position.tsv", sep = "\t", header = TRUE)
```


### Define lengths of adapter

```{r}
a60_unmod["adapter_length"] <- a60_unmod$start - 1
a60_30["adapter_length"] <- a60_30$start - 1
a60_60["adapter_length"] <- a60_60$start - 1

a120_unmod["adapter_length"] <- a120_unmod$start - 1
a120_1mod["adapter_length"] <- a120_1mod$start - 1
a120_2mod["adapter_length"] <- a120_2mod$start - 1
a120_4mod["adapter_length"] <- a120_4mod$start - 1
```


### Histograms of all the data in each set

```{r}
datasets <- list(
  a60_30 = a60_30,
  a60_60 = a60_60,
  a60_unmod = a60_unmod,
  a120_1mod = a120_1mod,
  a120_2mod = a120_2mod,
  a120_4mod = a120_4mod,
  a120_unmod = a120_unmod
)

for (name in names(datasets)) {
  adapter_length <- datasets[[name]]$adapter_length
  
  hist(adapter_length, 
       probability = TRUE, 
       main = paste("Density Plot of adapter lengths -", name), 
       xlab = "Adapter length", 
       ylab = "Density", 
       xlim = c(0, 8000),
       ylim = c(0, 0.0013),
       col = "lightblue",
       border = "black",         
       breaks = 200)              
  
  lines(density(adapter_length), col = "red", lwd = 2)
}
```


### Histograms of all the data with log transformation

```{r}
for (name in names(datasets)) {
  adapter_length <- datasets[[name]]$adapter_length
  
  # Remove values ≤ 0
  adapter_length <- adapter_length[adapter_length > 0]
  
  log_adapter_length <- log10(adapter_length) 
  
  hist(log_adapter_length, 
       probability = TRUE, 
       main = paste("Density Plot of log-transformed adapter lengths -", name), 
       xlab = "Log10(Adapter Length)",
       ylab = "Density", 
       border = "black", 
       col = "lightblue",
       xlim = c(3, 4),
       ylim = c(0, 7),
       breaks = 100)                  
  
  lines(density(log_adapter_length), col = "red", lwd = 2)
}
```


